---
- name: Install grub for EFI
  ansible.builtin.command:
    cmd: '{{ grub_efi_install_command }}'
  register: grub_efi_install_result
  changed_when: grub_efi_install_result.rc == 0
  notify: Regenerate GRUB config
