---
hostname: '{{ keystone.network.hostname }}'
locale: '{{ keystone.system.locale }}'
keymap: '{{ keystone.system.keymap }}'
mkinitcpio_hooks: '{{ keystone.mkinitcpio_hooks }}'

file:
  release: '{{ system_root }}/etc/arch-release'
  fstab: '{{ system_root }}/etc/fstab'
  localtime: '{{ system_root }}/etc/localtime'
  hardware_clock: '{{ system_root }}/etc/adjtime'
  hostname: '{{ system_root }}/etc/hostname'
  locale_gen: '{{ system_root }}/etc/locale.gen'
  locale_conf: '{{ system_root }}/etc/locale.conf'
  vconsole_conf: '{{ system_root }}/etc/vconsole.conf'
  mkinitcpio: '{{ system_root }}/etc/mkinitcpio.conf'
  sudoers: '{{ system_root }}/etc/sudoers'
  luks_keyfile_dir: '{{ system_root }}/etc/cryptsetup-keys.d'
  luks_keyfile: '{{ system_root }}/etc/cryptsetup-keys.d/non-root.key'

base_system_packages:
  - base
  - base-devel
  - linux
  - linux-firmware
  - lvm2
  - python
  - git

network_manager:
  package: networkmanager
  service: NetworkManager

command:
  pacstrap: 'pacstrap -K {{ system_root }} {{ base_system_packages | join(" ") }}'
  genfstab: 'genfstab -U {{ system_root }}'
  hwclock: '{{ chroot_command }} hwclock --systohc'
  locale_gen: '{{ chroot_command }} locale-gen'
  mkinitcpio: '{{ chroot_command }} mkinitcpio -P'

timezone_file: '{{ system_root }}/usr/share/zoneinfo/{{ keystone.system.time_region }}'
luks_keyfile_size: 512B
