---
- name: Initialize the SWAP partition
  community.general.filesystem:
    dev: '{{ keystone.swap_device }}'
    fstype: swap

- name: Add SWAP to fstab
  ansible.posix.mount:
    path: none
    src: '{{ keystone.swap_device }}'
    fstype: swap
    opts: sw
    state: present
