---
- name: Create the volume group
  community.general.lvg:
    vg: '{{ keystone.disks.lvm_config.vg_name }}'
    pvs: '{{ keystone.lvm_pv_device }}'
    pesize: '{{ keystone.lvm_pesize }}'

- name: Create logical volumes
  community.general.lvol:
    vg: '{{ keystone.disks.lvm_config.vg_name }}'
    lv: '{{ item.lv }}'
    size: '{{ item.size }}'
  loop: '{{ keystone.lvm_volumes_plan }}'
