---
- name: Create and open the LUKS container
  community.crypto.luks_device:
    device: '{{ item.device }}'
    state: opened
    name: '{{ item.name }}'
    passphrase: "{{ lookup('env', keystone.encryption_luks_passphrase_env_var) }}"
  loop: '{{ keystone.encryption_plan }}'
  no_log: true
