---
- name: Mount the partitions
  ansible.posix.mount:
    path: '{{ item.path }}'
    src: '{{ item.src }}'
    fstype: '{{ item.fstype }}'
    state: ephemeral
  changed_when: false
  loop: '{{ keystone.mount_plan }}'
