---
- name: Create the partitions
  community.general.parted:
    device: '{{ disk }}'
    number: '{{ item.number }}'
    state: present
    unit: '{{ keystone.parted_unit }}'
    label: '{{ item.label }}'
    flags: '{{ item.flags }}'
    part_start: '{{ item.part_start ~ keystone.parted_unit }}'
    part_end: '{{ item.part_end ~ keystone.parted_unit }}'
  loop: '{{ keystone.partition_plan }}'
