---
- name: Keystone install
  hosts: arch_iso
  gather_facts: true
  tasks:
    - name: Print a value pulled from keystone_config extravars
      ansible.builtin.debug:
        msg: "hostname from config: {{ keystone_config.network.hostname }}"
