---
- name: Install the base system
  hosts:
    - arch_iso
  roles:
    - check
    - setup_disks
    # - base_system
    # - boot

# - name: Setup the desktop environment
#   hosts:
#     - arch_chroot
#   roles:
#     - desktop_environment
