---
- name: Edit locale.gen file
  ansible.builtin.lineinfile:
    path: '{{ file.locale_gen }}'
    regexp: '^#.*{{ locale }}'
    line: '{{ locale }}'
    state: present
  notify:
    - Generate locale

- name: Set configuration files for locale and vconsole
  ansible.builtin.copy:
    dest: '{{ item.dest }}'
    content: '{{ item.content }}'
    mode: '0644'
  loop:
    - dest: '{{ file.locale_conf }}'
      content: "LANG={{ locale }}\n"
    - dest: '{{ file.vconsole_conf }}'
      content: "KEYMAP={{ keymap }}\n"
