---
- name: Add needed HOOKS in initramfs (only for encrypted and/or LVM layouts)
  ansible.builtin.lineinfile:
    path: '{{ file.mkinitcpio }}'
    regexp: '^HOOKS='
    line: 'HOOKS=({{ keystone.mkinitcpio_hooks | join(" ") }})'
    backrefs: true
  notify:
    - Generate the initramfs image
